// Login Form
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';

// Employee Create
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const CLEAR_EMPLOYEE = 'CLEAR_EMPLOYEE';
// export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE';
export const EMPLOYEE_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS';
export const FETCHING_EMPLOYEES = 'FETCHING_EMPLOYEES';
